const fs = require("fs")
const FE = require("path").join(__dirname, "..", "..", "frontend") + "/"
const css = fs.readFileSync(FE + "src/styles/linear-tokens.css", "utf8")
const vue = fs.readFileSync(FE + "src/views/KoreaLanding.vue", "utf8")
const scoped = (vue.match(/<style scoped>([\s\S]*?)<\/style>/) || [])[1] || ""

const heroStats = [["이번 달 급여","124,800,000원","직원 48명 · 예시",0],["대장 대비 오차","0원","1원 단위 일치",1],["명세서 발송","48 / 48","자동 발송",0]]
const features = [["₩","급여 자동 계산","월급제·시급제·일용직 급여를 사업장 규칙대로 계산하고, 확정 대장과 1원 단위로 대조합니다."],["🛡","4대보험 신고","취득·상실·근로내용확인 신고서를 서식 그대로 자동 생성. 사람 승인 게이트를 거쳐 제출합니다."],["🤖","AI HR 담당자","연차·급여·노동법 문의를 조문 근거와 함께 응답. 5채널."],["📄","임금명세서","근로기준법 제48조제2항 요건 충족 명세서를 자동 생성."],["📊","급여 마감 워크플로","업로드→검증→미리보기→승인. 확정 전에는 어떤 숫자도 반영되지 않습니다."],["🔒","테넌트 격리","사업장마다 독립 데이터 · 개인정보 암호화 · 감사 로그."]]
const plans = [["스타터","무료","~5인","소규모 사업장 · 급여·명세서 기본",["급여 자동계산","임금명세서 PDF","직원 셀프 조회"],"무료 시작",0],["프로","월 3만원~","인원 비례","4대보험 신고 + AI HR 담당자 5채널",["스타터 전체","4대보험 신고 3종","AI HR 담당자","급여 마감 승인"],"프로 시작",1],["엔터프라이즈","문의","다사업장","노무법인·다사업장 · 전용 지원",["프로 전체","다사업장 관리","전용 온보딩","SLA·우선지원"],"상담 요청",0]]
const verify = [["직원 A","3,120,400원"],["직원 B","2,845,900원"],["직원 C","3,507,120원"]]
const chans = ["텔레그램","이메일","슬랙","디스코드","구글챗"]

const statCards = heroStats.map(([l,v,n,a]) => `<div class="ln-card" style="padding:20px"><div class="ln-caption" style="color:var(--ln-ink-subtle)">${l}</div><div class="ln-num ${a?"ln-num--accent":""}">${v}</div><div class="ln-caption" style="margin-top:4px;color:var(--ln-ink-tertiary)">${n}</div></div>`).join("")
const featCards = features.map(([i,t,b]) => `<article class="ln-card ln-card--edge"><div class="ln-ficon">${i}</div><h3 class="ln-card-title" style="margin-top:16px;color:var(--ln-ink)">${t}</h3><p class="ln-body-sm" style="margin-top:8px">${b}</p></article>`).join("")
const verRows = verify.map(([n,a]) => `<div class="ln-verify-row"><span class="ln-body-sm" style="color:var(--ln-ink-muted)">${n}</span><span class="ln-num-sm ln-num--accent">${a}</span><span class="ln-status-badge"><span class="ln-dot"></span>1원 일치</span></div>`).join("")
const chips = chans.map(c => `<span class="ln-chip">${c}</span>`).join("")
const planCards = plans.map(([n,pr,u,d,fs2,cta,ft]) => `<article class="ln-card ${ft?"ln-card-lift ln-card--edge":""}"><div style="display:flex;align-items:center;gap:8px"><h3 class="ln-card-title" style="color:var(--ln-ink)">${n}</h3>${ft?'<span class="ln-status-badge" style="margin-left:auto;color:var(--ln-primary);border-color:var(--ln-primary)">추천</span>':""}</div><div style="margin-top:16px;display:flex;align-items:baseline;gap:6px"><span class="ln-num">${pr}</span><span class="ln-caption">${u}</span></div><p class="ln-body-sm" style="margin-top:8px;min-height:40px">${d}</p><ul class="ln-checklist" style="margin-top:16px">${fs2.map(x=>`<li><span class="ln-check">✓</span>${x}</li>`).join("")}</ul><a class="ln-btn ${ft?"ln-btn-primary":"ln-btn-secondary"}" href="#signup" style="width:100%;margin-top:20px">${cta}</a></article>`).join("")

const html = `<!doctype html><html><head><meta charset="utf8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{margin:0;box-sizing:border-box}html{scroll-behavior:smooth}${css}${scoped}</style></head><body class="linear">
<nav class="ln-nav"><div class="ln-container" style="height:56px;display:flex;align-items:center;justify-content:space-between"><div style="display:flex;align-items:center;gap:8px"><span class="ln-mark"></span><span style="font-family:var(--ln-font-display);font-weight:600;letter-spacing:-.02em;font-size:1.0625rem">SafeClaw HR</span></div><div class="ln-navlinks"><a class="ln-link" href="#features">기능</a><a class="ln-link" href="#accuracy">정확성</a><a class="ln-link" href="#pricing">요금</a><a class="ln-link" href="#ai">AI 담당자</a></div><div style="display:flex;gap:8px"><a class="ln-btn ln-btn-tertiary" href="#login">로그인</a><a class="ln-btn ln-btn-primary" href="#signup">시작하기</a></div></div></nav>
<header class="ln-hero-glow"><div class="ln-container ln-section" style="text-align:center"><span class="ln-status-badge" style="margin-bottom:20px"><span class="ln-dot"></span>한국 노무 특화 · 급여부터 4대보험까지 하나로</span><h1 class="ln-display-xl" style="color:var(--ln-ink)">틀리면 안 되는 급여를<br>1원 단위로.</h1><p class="ln-body-lg" style="max-width:52ch;margin:20px auto 0">한국 노무에 특화된 HR SaaS. 급여·4대보험 신고·명세서를 자동으로 처리하고, AI HR 담당자가 텔레그램·메일·슬랙에서 직원 문의에 바로 답합니다.</p><div style="display:flex;gap:12px;justify-content:center;margin-top:32px;flex-wrap:wrap"><a class="ln-btn ln-btn-primary" href="#signup" style="min-height:44px;padding:12px 20px">사업장 무료로 시작</a><a class="ln-btn ln-btn-secondary" href="#accuracy" style="min-height:44px;padding:12px 20px">정확성 원리 보기</a></div><div class="ln-screenshot ln-card--edge" style="margin-top:56px;text-align:left"><div style="display:flex;align-items:center;gap:8px;margin-bottom:16px"><span class="ln-mono" style="color:var(--ln-ink-subtle)">급여 마감 미리보기 · 예시</span><span class="ln-status-badge" style="margin-left:auto"><span class="ln-dot"></span>확정</span></div><div class="ln-grid-3">${statCards}</div></div></div></header>
<section id="features" class="ln-container ln-section"><div style="max-width:44ch;margin-bottom:40px"><div class="ln-eyebrow">플랫폼</div><h2 class="ln-display-md" style="margin-top:12px;color:var(--ln-ink)">급여실무 전 과정을 한 곳에서</h2></div><div class="ln-grid-3">${featCards}</div></section>
<section id="accuracy" style="background:var(--ln-surface-1);border-top:1px solid var(--ln-hairline);border-bottom:1px solid var(--ln-hairline)"><div class="ln-container ln-section ln-two-col"><div><div class="ln-eyebrow">정확성</div><h2 class="ln-display-md" style="margin-top:12px;color:var(--ln-ink)">숫자는 흔들리지 않는다</h2><p class="ln-body" style="margin-top:16px">모든 급여는 확정 대장과 1원 단위로 크로스체크한 뒤에만 반영됩니다. 엔진과 엑셀이 다르면 엑셀이 권위 — 사유를 분석하고 엔진을 고칩니다.</p><ul class="ln-checklist"><li><span class="ln-check">✓</span>엑셀이 권위</li><li><span class="ln-check">✓</span>확정 행위는 사람 승인 게이트</li><li><span class="ln-check">✓</span>모든 변경은 results 저널 기록</li></ul></div><div class="ln-screenshot ln-card--edge"><div class="ln-mono" style="color:var(--ln-ink-subtle);margin-bottom:12px">검증 로그 · results</div>${verRows}</div></div></section>
<section class="ln-container ln-section"><div style="text-align:center;max-width:52ch;margin:0 auto 40px"><div class="ln-eyebrow" id="ai">AI HR 담당자</div><h2 class="ln-display-md" style="margin-top:12px;color:var(--ln-ink)">직원 문의에 24시간 바로 답합니다</h2></div><div style="display:flex;gap:12px;flex-wrap:wrap;justify-content:center">${chips}</div></section>
<section id="pricing" style="background:var(--ln-surface-1);border-top:1px solid var(--ln-hairline)"><div class="ln-container ln-section"><div style="text-align:center;max-width:44ch;margin:0 auto 40px"><div class="ln-eyebrow">요금</div><h2 class="ln-display-md" style="margin-top:12px;color:var(--ln-ink)">사업장 규모에 맞게</h2></div><div class="ln-grid-3">${planCards}</div></div></section>
<section id="signup" class="ln-container ln-section"><div class="ln-cta-banner ln-card--edge" style="max-width:640px;margin:0 auto"><h2 class="ln-headline" style="color:var(--ln-ink)">2분이면 사업장이 열립니다</h2><p class="ln-body" style="margin-top:12px">사업장명과 이메일을 남기면 하루 안에 전용 사업장 주소를 만들어 안내드립니다.</p><div class="ln-form"><div style="text-align:left"><label class="ln-label" for="sc-company">사업장명</label><input id="sc-company" class="ln-input" placeholder="예: (주)윈하이어"></div><div style="text-align:left"><label class="ln-label" for="sc-email">담당자 이메일</label><input id="sc-email" class="ln-input" type="email" placeholder="you@company.com"></div><button class="ln-btn ln-btn-primary" type="button" onclick="scApply()" style="width:100%;min-height:44px">무료로 사업장 신청</button><p class="ln-caption">버튼을 누르면 메일 앱이 열립니다 · 직접 문의: <a class="ln-link ln-link--accent" href="mailto:abc@winhr.co.kr">abc@winhr.co.kr</a></p></div></div>
<p id="login" class="ln-caption" style="text-align:center;margin-top:40px">이미 이용 중이신가요? 각 사업장 전용 주소(<span class="ln-mono">회사명.safeclaw.kr</span>)로 접속해 로그인하세요.</p>
<script>function scApply(){var c=document.getElementById("sc-company").value.trim();var e=document.getElementById("sc-email").value.trim();var s=encodeURIComponent("[SafeClaw HR] 사업장 개설 신청 — "+(c||"사업장명 미기재"));var b=encodeURIComponent("사업장명: "+c+"
담당자 이메일: "+e+"

(추가로 궁금한 점을 적어주세요)");location.href="mailto:abc@winhr.co.kr?subject="+s+"&body="+b}</script></section>
<footer class="ln-footer"><div class="ln-container" style="display:flex;justify-content:space-between;gap:32px;flex-wrap:wrap"><div><div style="font-family:var(--ln-font-display);font-weight:600;color:var(--ln-ink)">SafeClaw HR</div><p class="ln-caption" style="margin-top:8px">한국 노무 특화 HR SaaS</p></div></div></footer>
</body></html>`

const out = require("path").join(__dirname, "safeclaw-hr.html")
fs.writeFileSync(out, html)
console.log("WROTE", out, html.length, "bytes")
